### ISSUE TITLE
it crashes

### ISSUE THREAD

**Issue by weedplant** [xmrig/xmrig-aeon#1]
Hello,

How come that xmrig-aeon.exe is 6 times faster than all the other xmrigs?
I want to use this program but it keeps crashing after a while. I have to restart my computer to run it again. If I don't restart it wont do anything anymore. I tried the other xmrigs but they are much much slower. With xmrig-aeon i've been getting 300 h/s and with the other one's I'll get 56 h/s
It crashes on every computer I tried. I can use the other one's stable but the hashrates are poor.
I'm using windows. I tried Windows Vista, Win 7, Win 8 and Win 10. 
Tried on i5 , i3 , core 2 duo

Thanks

**Comment by xmrig** [comment]
This miner use `cryptonight-lite` this algorithm give more hashrate, but it usable only for AEON coin.
This algorithm implemented in all xmrig miners you can use it via `--algo cryptonight-lite` option.
This repository is deprecated and there will no updates.
Thank you.
